---
name: Build AppImage executable

on:
  - push

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run build container
        uses: c0xc/qt-build-appimage-test@master
        with:
          recipe: .build_pipe_vars
          os_name: fedora
          #env: |
          #  os_name=Fedora
          #build-args: |
          #  OS_NAME=${{ env.OS_NAME }}
          #  OS_RELEASE=${{ env.OS_RELEASE }}
          #  os_name=FEDORA
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: |
            build.tar
            #bin/*
            #*.AppImage
