---
name: C/C++ AppImage


on:
  - push
  - pull_request

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtdeclarative5-dev qttools5-dev-tools 
      - name: configure
        run: qmake CONFIG+=release PREFIX=/usr
      - name: build
        run: INSTALL_ROOT=./AppDir make install
      - name: desktop
        run: cp -vi capacitytester.desktop USB_flash_drive.png AppDir/
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
          UPDATE_INFO: gh-releases-zsync|c0xc|CapacityTester|latest|*x86_64.AppImage.zsync
        with:
          recipe: .AppImageBuilder.yml
      
